name: Continuous Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: shareits
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U developer"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    env:
      DATABASE_URL: postgresql://developer:developer@localhost:5432/shareits
      JWT_SECRET: d3a2b276f84e9809d39b772f33435ffa1bbf077dd4d8e15a448ec6990814d005
      NODE_ENV: development
      PORT: 8080
      HOST: localhost
      CORS_ORIGIN: http://localhost:*
      COMMON_RATE_LIMIT_WINDOW_MS: 1000
      COMMON_RATE_LIMIT_MAX_REQUESTS: 20
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_USER: postmaster@sandbox8b0e11ea5e784d3c964c57c7fb24d1b1.mailgun.org
      SMTP_PASS: 021637a9ea349cf4e4ee7d5156355932-72e4a3d5-fdff2ae1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Run Linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run migrations
        run: npm run prisma:migrate

      - name: Run tests
        run: npm test